### ISSUE TITLE
Credenciales en el Repo

### ISSUE THREAD

**Issue by Diego-II** [paul-ltr/neuralworks-ml-challenge#4]
https://github.com/paul-ltr/neuralworks-ml-challenge/blob/ba69240e55f97d4ed321dda1f9eee8bb3a79a74a/Jenkinsfile#L26

Hola Paul! Diego aca, de Neuralworks. Oye, ojo con esto... tienes tus credenciales de AWS versionadas en codigo publico. Con esto personas pueden levantar infra en tu cuenta sin que lo notes y terminar con una cuenta enorme. Trata de hacer algo con github secrets o, seguro con Jenkins se puede hacer alguna integracion con AWS.

**Comment by paul-ltr** [comment]
Hola Diego! Muchas gracias por el consejo, he utilizado un git-filter-repo para eliminar el archivo del repo !
